name: "Setup Custom Java"
description: "Set up JDK 17, Maven, and Maven settings"
author: "Your Name or Organization"
inputs:
  java-version:
    description: "Version of Java to set up"
    required: false
    default: "17"
  distribution:
    description: "Java distribution to use"
    required: false
    default: "temurin"
  maven-server-id:
    description: "Maven server ID"
    required: true
  maven-server-username:
    description: "Maven server username"
    required: true
  maven-server-password:
    description: "Maven server password"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: "${{ inputs.java-version }}"
        distribution: "${{ inputs.distribution }}"
        cache: maven

    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install -y maven

    - name: Configure Maven Settings
      uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: |
          [
            {
              "id": "${{ inputs.maven-server-id }}",
              "username": "${{ inputs.maven-server-username }}",
              "password": "${{ inputs.maven-server-password }}"
            }
          ]
