name: Setup Custom Java

on:
  workflow_dispatch: # Allow manual triggering of this action

jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 2: Install Maven
      - name: Set up Maven
        run: |
          sudo apt update
          sudo apt install -y maven          

      # Step 3: Configure Maven settings
      - name: Configure Maven settings
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: >
            [{"id": "${{ env.MAVEN_SERVER_ID }}",
              "username": "${{ env.MAVEN_SERVER_USERNAME }}",
              "password": "${{ env.MAVEN_SERVER_PASSWORD }}"}]
